package com.example.hoanglong.letstakeaflagquiz;

public class Database {
    Integer[] flags = {
           R.drawable.afghanistan,
            R.drawable.armenia,
            R.drawable.australia,
            R.drawable.azerbaijan,
            R.drawable.bahrain,
            R.drawable.bangladesh,
            R.drawable.bhutan,
            R.drawable.brunei,
            R.drawable.cambodia,
            R.drawable.canada,
            R.drawable.china,
            R.drawable.cyprus,
            R.drawable.france,
            R.drawable.georgia,
            R.drawable.germany,
            R.drawable.india,
            R.drawable.indonesia,
            R.drawable.iran,
            R.drawable.iraq,
            R.drawable.israel,
            R.drawable.japan,
            R.drawable.jordan,
            R.drawable.kazakhstan,
            R.drawable.kuwait,
            R.drawable.kyrgyzstan,
            R.drawable.laos,
            R.drawable.lebanon,
            R.drawable.malaysia,
            R.drawable.maldives,
            R.drawable.mexico,
            R.drawable.mongolia,
            R.drawable.myanmar,
            R.drawable.nepal,
            R.drawable.north_korea,
            R.drawable.oman,
            R.drawable.pakistan,
            R.drawable.philippines,
            R.drawable.qatar,
            R.drawable.russian_federation,
            R.drawable.saudi_arabia,
            R.drawable.singapore,
            R.drawable.south_korea,
            R.drawable.sri_lanka,
            R.drawable.syria,
            R.drawable.taiwan,
            R.drawable.tajikistan,
            R.drawable.thailand,
            R.drawable.timor_leste,
            R.drawable.turkey,
            R.drawable.turkmenistan,
            R.drawable.united_arab_emirates,
            R.drawable.united_kingdom,
            R.drawable.united_states,
            R.drawable.uzbekistan,
            R.drawable.vietnam,
            R.drawable.yemen,
            R.drawable.albania,
            R.drawable.andorra,
            R.drawable.antigua_and_barbuda,
            R.drawable.austria,
            R.drawable.bahamas,
            R.drawable.barbados,
            R.drawable.belarus,
            R.drawable.belgium,
            R.drawable.belize,
            R.drawable.bosnia,
            R.drawable.bulgaria,
            R.drawable.costa_rica,
            R.drawable.croatia,
            R.drawable.cuba,
            R.drawable.czech_republic,
            R.drawable.denmark,
            R.drawable.dominica,
            R.drawable.dominican_republic,
            R.drawable.el_salvador,
            R.drawable.estonia,
            R.drawable.fiji,
            R.drawable.finland,
            R.drawable.greece,
            R.drawable.grenada,
            R.drawable.guatemala,
            R.drawable.haiti,
            R.drawable.honduras,
            R.drawable.hungary,
            R.drawable.iceland,
            R.drawable.italy,
            R.drawable.jamaica,
            R.drawable.kiribati,
            R.drawable.kosovo,
            R.drawable.latvia,
            R.drawable.liechtenstein,
            R.drawable.lithuania,
            R.drawable.luxembourg,
            R.drawable.macedonia,
            R.drawable.malta,
            R.drawable.marshall_islands,
            R.drawable.micronesia,
            R.drawable.moldova,
            R.drawable.monaco,
            R.drawable.montenegro,
            R.drawable.nauru,
            R.drawable.netherlands,
            R.drawable.new_zealand,
            R.drawable.nicaragua,
            R.drawable.norway,
            R.drawable.palau,
            R.drawable.panama,
            R.drawable.papua_new_guinea,
            R.drawable.poland,
            R.drawable.portugal,
            R.drawable.romania,
            R.drawable.saint_kitts_and_nevis,
            R.drawable.saint_lucia,
            R.drawable.saint_vicent_and_the_grenadines,
            R.drawable.san_marino,
            R.drawable.serbia,
            R.drawable.slovakia,
            R.drawable.slovenia,
            R.drawable.spain,
            R.drawable.sweden,
            R.drawable.switzerland,
            R.drawable.trinidad_and_tobago,
            R.drawable.ukraine,
            R.drawable.vatican_city,
            R.drawable.algeria,
            R.drawable.angola,
            R.drawable.argentina,
            R.drawable.benin,
            R.drawable.bolivia,
            R.drawable.botswana,
            R.drawable.brazil,
            R.drawable.burkina_faso,
            R.drawable.burundi,
            R.drawable.cameroon,
            R.drawable.cape_verde,
            R.drawable.central_african_republic,
            R.drawable.chile,
            R.drawable.colombia,
            R.drawable.comoros,
            R.drawable.cote_divoire,
            R.drawable.democratic_republic_of_the_congo,
            R.drawable.djibouti,
            R.drawable.ecuador,
            R.drawable.egypt,
            R.drawable.equatorial_guinea,
            R.drawable.eritrea,
            R.drawable.ethiopia,
            R.drawable.gabon,
            R.drawable.gambia,
            R.drawable.ghana,
            R.drawable.guinea,
            R.drawable.guinea_bissau,
            R.drawable.guyana,
            R.drawable.kenya,
            R.drawable.lesotho,
            R.drawable.liberia,
            R.drawable.libya,
            R.drawable.madagascar,
            R.drawable.malawi,
            R.drawable.mali,
            R.drawable.mauritania,
            R.drawable.mauritius,
            R.drawable.morocco,
            R.drawable.mozambique,
            R.drawable.namibia,
            R.drawable.niger,
            R.drawable.nigeria,
            R.drawable.paraguay,
            R.drawable.peru,
            R.drawable.republic_of_the_congo,
            R.drawable.rwanda,
            R.drawable.samoa,
            R.drawable.sao_tome_and_principe,
            R.drawable.senegal,
            R.drawable.seychelles,
            R.drawable.sierra_leone,
            R.drawable.soloman_islands,
            R.drawable.somalia,
            R.drawable.south_africa,
            R.drawable.sudan,
            R.drawable.suriname,
            R.drawable.swaziland,
            R.drawable.tanzania,
            R.drawable.togo,
            R.drawable.tonga,
            R.drawable.tunisia,
            R.drawable.tuvalu,
            R.drawable.uganda,
            R.drawable.uruguay,
            R.drawable.vanuatu,
            R.drawable.venezuela,
            R.drawable.western_sahara,
            R.drawable.zambia,
            R.drawable.zimbabwe
    };
    String[] answers = {
            "Afghanistan",
            "Armenia",
            "Australia",
            "Azerbaijan",
            "Bahrain",
            "Bangladesh",
            "Bhutan",
            "Brunei",
            "Cambodia",
            "Canada",
            "China",
            "Cyprus",
            "France",
            "Georgia",
            "Germany",
            "India",
            "Indonesia",
            "Iran",
            "Iraq",
            "Israel",
            "Japan",
            "Jordan",
            "Kazakhstan",
            "Kuwait",
            "Kyrgyzstan",
            "Laos",
            "Lebanon",
            "Malaysia",
            "Maldives",
            "Mexico",
            "Mongolia",
            "Myanmar",
            "Nepal",
            "North Korea",
            "Oman",
            "Pakistan",
            "Philippines",
            "Qatar",
            "Russian Federation",
            "Saudi Arabia",
            "Singapore",
            "South Korea",
            "Sri Lanka",
            "Syria",
            "Taiwan",
            "Tajikistan",
            "Thailand",
            "Timor Leste",
            "Turkey",
            "Turkmenistan",
            "United Arab Emirates",
            "United Kingdom",
            "United States",
            "Uzbekistan",
            "Vietnam",
            "Yemen",
            "Albania",
            "Andorra",
            "Antigua and Barbuda",
            "Austria",
            "Bahamas",
            "Barbados",
            "Belarus",
            "Belgium",
            "Belize",
            "Bosnia",
            "Bulgaria",
            "Costa Rica",
            "Croatia",
            "Cuba",
            "Czech Republic",
            "Denmark",
            "Dominica",
            "Dominican Republic",
            "El Salvador",
            "Estonia",
            "Fiji",
            "Greece",
            "Grenada",
            "Guatemala",
            "Haiti",
            "Honduras",
            "Hungary",
            "Iceland",
            "Ireland",
            "Italy",
            "Jamaica",
            "Kiribati",
            "Kosovo",
            "Latvia",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Macedonia",
            "Malta",
            "Marshall Islands",
            "Micronesia",
            "Moldova",
            "Monaco",
            "Montenegro",
            "Nauru",
            "Netherlands",
            "New Zealand",
            "Nicaragua",
            "Norway",
            "Palau",
            "Panama",
            "Papua New Guinea",
            "Poland",
            "Portugal",
            "Romania",
            "Saint Kitts and Nevis",
            "Saint Lucia",
            "Saint Vicent and the Grenadines",
            "San Marino",
            "Serbia",
            "Slovakia",
            "Slovenia",
            "Spain",
            "Sweden",
            "Switzerland",
            "Trinidad and Tobago",
            "Ukraine",
            "Vatican City",
            "Algeria",
            "Angola",
            "Argentina",
            "Benin",
            "Bolivia",
            "Botswana",
            "Brazil",
            "Burkina Faso",
            "Burundi",
            "Cameroon",
            "Cape Verde",
            "Central African Republic",
            "Chile",
            "Colombia",
            "Comoros",
            "Cote Divoire",
            "Democratic Republic of the Congo",
            "Djibouti",
            "Ecuador",
            "Egypt",
            "Equatorial Guinea",
            "Eritrea",
            "Ethiopia",
            "Gabon",
            "Gambia",
            "Ghana",
            "Guinea",
            "Guinea Bissau",
            "Guyana",
            "Kenya",
            "Lesotho",
            "Liberia",
            "Libya",
            "Madagascar",
            "Malawi",
            "Mali",
            "Mauritania",
            "Mauritius",
            "Morocco",
            "Mozambique",
            "Namibia",
            "Niger",
            "Nigeria",
            "Paraguay",
            "Peru",
            "Republic of the Congo",
            "Rwanda",
            "Samoa",
            "Sao Tome and Principe",
            "Senegal",
            "Seychelles",
            "Sierra Leone",
            "Soloman Islands",
            "Somalia",
            "South Africa",
            "Sudan",
            "Suriname",
            "Swaziland",
            "Tanzania",
            "Togo",
            "Tonga",
            "Tunisia",
            "Tuvalu",
            "Uganda",
            "Uruguay",
            "Vanuatu",
            "Venezuela",
            "Western Sahara",
            "Zambia",
            "Zimbabwe"
    };
}